apiVersion: "v1"
kind: "Schema"
metadata:
  name: "abc.header-value"
spec:
  schema: |
    {
      "namespace": "io.github.michelin.ns4kafka.avro",
      "type": "record",
      "name": "KafkaHeader",
      "fields": [
        {
          "name": "id",
          "type": "long"
        }
      ]
    }
---
apiVersion: "v1"
kind: "Schema"
metadata:
  name: "abc.person-value"
spec:
  schema: |
    {
      "namespace": "io.github.michelin.ns4kafka.avro",
      "type": "record",
      "name": "KafkaPerson",
      "fields": [
        {
          "name": "header",
          "type": "io.github.michelin.ns4kafka.avro.KafkaHeader"
        },
        {
          "name": "firstName",
          "type": "string"
        },
        {
          "name": "lastName",
          "type": "string"
        }
      ]
    }
  references:
  - name: "io.github.michelin.ns4kafka.avro.KafkaHeader"
    subject: "abc.header-value"
    version: 1
