apiVersion: "v1"
kind: "Schema"
metadata:
  name: "abc.header-value"
spec:
  schema: "{\n  \"namespace\": \"io.github.michelin.ns4kafka.avro\",\n  \"type\":\
    \ \"record\",\n  \"name\": \"KafkaHeader\",\n  \"fields\": [\n    {\n      \"\
    name\": \"id\",\n      \"type\": \"long\"\n    }\n  ]\n}\n"
---
apiVersion: "v1"
kind: "Schema"
metadata:
  name: "abc.person-value"
spec:
  schema: "{\n  \"namespace\": \"io.github.michelin.ns4kafka.avro\",\n  \"type\":\
    \ \"record\",\n  \"name\": \"KafkaPerson\",\n  \"fields\": [\n    {\n      \"\
    name\": \"header\",\n      \"type\": \"io.github.michelin.ns4kafka.avro.KafkaHeader\"\
    \n    },\n    {\n      \"name\": \"firstName\",\n      \"type\": \"string\"\n\
    \    },\n    {\n      \"name\": \"lastName\",\n      \"type\": \"string\"\n  \
    \  }\n  ]\n}\n"
  references:
  - name: "io.github.michelin.ns4kafka.avro.KafkaHeader"
    subject: "abc.header-value"
    version: 1
