kafkactl:
  api: 'http://ns4kafka:8080'
  contexts:
    - context:
        api: 'http://ns4kafka:8080'
        namespace: 'myNamespace'
        user-token: 'admin'
      name: 'local'
  current-namespace: 'myNamespace'
  user-token: 'admin'