---
apiVersion: v1
kind: Namespace
metadata:
  name: anotherNamespace
  cluster: local
  labels:
    contacts: namespace.owner@example.com
spec:
  kafkaUser: user2
  connectClusters:
    - local
  topicValidator:
    validationConstraints:
      partitions:
        validation-type: Range
        min: 1
        max: 6
      replication.factor:
        validation-type: Range
        min: 1
        max: 1
      min.insync.replicas:
        validation-type: Range
        min: 1
        max: 1
      retention.ms:
        optional: true
        validation-type: Range
        min: 60000
        max: 604800000
      cleanup.policy:
        validation-type: ValidList
        validStrings:
          - delete
          - compact
  connectValidator:
    validationConstraints:
      key.converter:
        validation-type: NonEmptyString
      value.converter:
        validation-type: NonEmptyString
      connector.class:
        validation-type: ValidString
        validStrings:
          - io.confluent.connect.jdbc.JdbcSinkConnector
          - io.confluent.connect.jdbc.JdbcSourceConnector
          - io.confluent.kafka.connect.datagen.DatagenConnector
    classValidationConstraints:
      io.confluent.kafka.connect.datagen.DatagenConnector:
        schema.string:
          validation-type: NonEmptyString
        schema.keyfield:
          validation-type: NonEmptyString
---
apiVersion: v1
kind: RoleBinding
metadata:
  name: anotherRoleBinding1
  namespace: anotherNamespace
spec:
  role:
    resourceTypes:
    - schemas
    - schemas/config
    - topics
    - topics/import
    - topics/delete-records
    - connectors
    - connectors/import
    - connectors/change-state
    - connect-clusters
    - connect-clusters/vaults
    - acls
    - consumer-groups/reset
    - streams
    verbs:
    - GET
    - POST
    - PUT
    - DELETE
  subject:
    subjectType: GROUP
    subjectName: DEV
---
apiVersion: v1
kind: RoleBinding
metadata:
  name: anotherRoleBinding2
  namespace: anotherNamespace
spec:
  role:
    resourceTypes:
    - quota
    verbs:
    - GET
  subject:
    subjectType: GROUP
    subjectName: DEV
---
apiVersion: v1
kind: AccessControlEntry
metadata:
  name: anotherTopicAcl
  namespace: anotherNamespace
spec:
  resourceType: TOPIC
  resource: def.
  resourcePatternType: PREFIXED
  permission: OWNER
  grantedTo: anotherNamespace
---
apiVersion: v1
kind: AccessControlEntry
metadata:
  name: anotherGroupAcl
  namespace: anotherNamespace
spec:
  resourceType: GROUP
  resource: def.
  resourcePatternType: PREFIXED
  permission: OWNER
  grantedTo: anotherNamespace
---
apiVersion: v1
kind: AccessControlEntry
metadata:
  name: anotherConnectAcl
  namespace: anotherNamespace
spec:
  resourceType: CONNECT
  resource: def.
  resourcePatternType: PREFIXED
  permission: OWNER
  grantedTo: anotherNamespace
---
apiVersion: v1
kind: AccessControlEntry
metadata:
  name: anotherConnectClusterAcl
  namespace: anotherNamespace
spec:
  resourceType: CONNECT_CLUSTER
  resource: def.
  resourcePatternType: PREFIXED
  permission: OWNER
  grantedTo: anotherNamespace