apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "myNamespace"
  cluster: "local"
  labels:
    contacts: "namespace.owner@example.com"
spec:
  kafkaUser: "user1"
  transactionsEnabled: false
  connectClusters:
  - "local"
  topicValidator:
    validationConstraints:
      partitions:
        validation-type: "Range"
        min: 1
        max: 6
      replication.factor:
        validation-type: "Range"
        min: 1
        max: 1
      min.insync.replicas:
        validation-type: "Range"
        min: 1
        max: 1
      retention.ms:
        optional: true
        validation-type: "Range"
        min: 60000
        max: 604800000
      cleanup.policy:
        validation-type: "ValidList"
        validStrings:
        - "delete"
        - "compact"
  connectValidator:
    validationConstraints:
      key.converter:
        validation-type: "NonEmptyString"
      value.converter:
        validation-type: "NonEmptyString"
      connector.class:
        validation-type: "ValidString"
        validStrings:
        - "io.confluent.connect.jdbc.JdbcSinkConnector"
        - "io.confluent.connect.jdbc.JdbcSourceConnector"
        - "io.confluent.kafka.connect.datagen.DatagenConnector"
    classValidationConstraints:
      io.confluent.kafka.connect.datagen.DatagenConnector:
        schema.string:
          validation-type: "NonEmptyString"
        schema.keyfield:
          validation-type: "NonEmptyString"
---
apiVersion: "v1"
kind: "RoleBinding"
metadata:
  name: "myRoleBinding1"
  namespace: "myNamespace"
spec:
  role:
    resourceTypes:
    - "schemas"
    - "schemas/config"
    - "topics"
    - "topics/import"
    - "topics/delete-records"
    - "connectors"
    - "connectors/import"
    - "connectors/change-state"
    - "connect-clusters"
    - "connect-clusters/vaults"
    - "acls"
    - "consumer-groups/reset"
    - "streams"
    verbs:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  subject:
    subjectType: "GROUP"
    subjectName: "ns4kafka"
---
apiVersion: "v1"
kind: "RoleBinding"
metadata:
  name: "myRoleBinding2"
  namespace: "myNamespace"
spec:
  role:
    resourceTypes:
    - "quota"
    verbs:
    - "GET"
  subject:
    subjectType: "GROUP"
    subjectName: "ns4kafka"
---
apiVersion: "v1"
kind: "AccessControlEntry"
metadata:
  name: "myTopicAcl"
  namespace: "myNamespace"
spec:
  resourceType: "TOPIC"
  resource: "abc."
  resourcePatternType: "PREFIXED"
  permission: "OWNER"
  grantedTo: "myNamespace"
---
apiVersion: "v1"
kind: "AccessControlEntry"
metadata:
  name: "myGroupAcl"
  namespace: "myNamespace"
spec:
  resourceType: "GROUP"
  resource: "abc."
  resourcePatternType: "PREFIXED"
  permission: "OWNER"
  grantedTo: "myNamespace"
---
apiVersion: "v1"
kind: "AccessControlEntry"
metadata:
  name: "myConnectAcl"
  namespace: "myNamespace"
spec:
  resourceType: "CONNECT"
  resource: "abc."
  resourcePatternType: "PREFIXED"
  permission: "OWNER"
  grantedTo: "myNamespace"
---
apiVersion: "v1"
kind: "AccessControlEntry"
metadata:
  name: "myConnectClusterAcl"
  namespace: "myNamespace"
spec:
  resourceType: "CONNECT_CLUSTER"
  resource: "abc."
  resourcePatternType: "PREFIXED"
  permission: "OWNER"
  grantedTo: "myNamespace"
