akhq:
  connections:
    kafka-cluster-1:
      connect:
        - name: 'local'
          url: 'http://connect:8083'
      properties:
        bootstrap.servers: 'broker:29092'
        sasl.jaas.config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin";'
        sasl.mechanism: 'SCRAM-SHA-512'
        security.protocol: 'SASL_PLAINTEXT'
      schema-registry:
        url: 'http://schema-registry:8081'